<?php
    $day_off = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getDayOff();
    $block_out_holidays = unserialize($this->helper('Bss\OrderDeliveryDate\Helper\Data')->getBlockHoliday());
    $process_time = 0;
    $current_time = (int) $block->getStoreTimestamp();
    $cut_off_time_convert = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getCutOffTime();
    $process_time = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getProcessingTime();
    if($cut_off_time_convert && $current_time > $cut_off_time_convert){
        $process_time = $process_time + 1;
    }

  $shippincity = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getShippingState();


  $datecount = 0;
$allRegionArray = array();

$allRegionArray['Alberta'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->abState();

$allRegionArray['British Columbia'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->bcState();

$allRegionArray['Manitoba'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->mbState();

 $allRegionArray['New Brunswick'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->nbState();

 $allRegionArray['Newfoundland and Labrador'] =  $this->helper('Bss\OrderDeliveryDate\Helper\Data')->nlState();

 $allRegionArray['Nova Scotia'] =$this->helper('Bss\OrderDeliveryDate\Helper\Data')->nsState();

 $allRegionArray['Northwest Territories'] =$this->helper('Bss\OrderDeliveryDate\Helper\Data')->ntState();

 $allRegionArray['Prince Edward Island'] =$this->helper('Bss\OrderDeliveryDate\Helper\Data')->peState();

 $allRegionArray['Quebec'] =$this->helper('Bss\OrderDeliveryDate\Helper\Data')->qcState();


 $allRegionArray['Saskatchewan'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->skState();

  $allRegionArray['Yukon Territory'] = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->ytState();

   $allRegionArray['Ontario'] =$this->helper('Bss\OrderDeliveryDate\Helper\Data')->onState();

$datecount = $allRegionArray[$shippincity];

//echo $day_off;
?>

<script>
    var trigger = false;
    var previousDate = "";
    var block_out_holidays = [];
    var day_off_arr = [];
var allRegion = [];
allRegion = '<?php echo json_encode($allRegionArray); ?>'
window.allRegion = allRegion;

    var day_off = '0';
    day_off_arr = day_off.split(',');
    block_out_holidays = '<?php echo json_encode($block_out_holidays);?>';
    require([
          'jquery',
          'mage/calendar'
        ], function ( $ ) {
          $.extend(true, $, {
            calendarConfig: { 
                minDate: '+0D',
                infoTitle: "<?php /* @escapeNotVerified */ echo __('About the calendar');?>",
                firstDay: 0,
                closeText: "<?php /* @escapeNotVerified */ echo __('Close');?>",
                currentText: "<?php /* @escapeNotVerified */ echo __('Go Today'); ?>",
                prevText: "<?php /* @escapeNotVerified */ echo __('Previous');?>",
                nextText: "<?php /* @escapeNotVerified */ echo __('Next');?>",
                weekHeader: "<?php /* @escapeNotVerified */ echo __('WK'); ?>",
                timeText: "<?php /* @escapeNotVerified */ echo __('Time');?>",
                hourText: "<?php /* @escapeNotVerified */ echo __('Hour');?>",
                minuteText: "<?php /* @escapeNotVerified */ echo __('Minute');?>",
                dateFormat: $.datepicker.RFC_2822,
                showOn: "both",
                showAnim: "",
                changeMonth: true,
                changeYear: true,
                buttonImageOnly: null,
                buttonImage: null,
                showButtonPanel: true,
           showOtherMonths: true,
                showWeek: false,
                timeFormat: '',
                showTime: false,
                showHour: false,
                showMinute: false,
                serverTimezoneSeconds: <?php echo (int) $block->getStoreTimestamp(); ?>,
                serverTimezoneOffset: <?php echo (int) $block->getTimezoneOffsetSeconds(); ?>,
              

            }
          });
        });
function checkFn(param){

}


</script>

